name: Build, Package, Release (staging)
'on':
  release:
    types:
      - created
  push:
    branches:
      - staging
env:
  VERSION: null
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.MO_REGISTRY_AUTH_URL__STAGING }}
          username: ${{ vars.MO_REGISTRY_USER__STAGING }}
          password: ${{ secrets.MO_REGISTRY_PAT__STAGING }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ${{ vars.MO_DOCKERCONTEXT__STAGING }}
          file: ${{ vars.MO_DOCKERFILE__STAGING }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.MO_IMAGE_NAME__STAGING }}:${{ env.VERSION }}
            ${{ vars.MO_IMAGE_NAME__STAGING }}:latest
          build-args: |
            VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-67f85ef645d1e12b3290
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__STAGING }}:${{ env.VERSION }}
          kind: Deployment
          namespace: behrang
          resourceName: franky-test-deployment
          containerName: franky-test-deployment
          keyKind: ${{ vars.MO_API_KIND__STAGING }}
          token: ${{ secrets.MO_API_TOKEN__67f85ef645d1e12b3290__STAGING }}
