name: Build, Package, Release (develop)
'on':
  release:
    types:
      - created
  push:
    branches:
      - develop
env:
  VERSION: null
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.MO_REGISTRY_AUTH_URL__DEVELOP }}
          username: ${{ vars.MO_REGISTRY_USER__DEVELOP }}
          password: ${{ secrets.MO_REGISTRY_PAT__DEVELOP }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ${{ vars.MO_DOCKERCONTEXT__DEVELOP }}
          file: ${{ vars.MO_DOCKERFILE__DEVELOP }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.MO_IMAGE_NAME__DEVELOP }}:${{ env.VERSION }}
            ${{ vars.MO_IMAGE_NAME__DEVELOP }}:latest
          build-args: |
            VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-f22d1e57db55edefd5ac
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__DEVELOP }}:${{ env.VERSION }}
          kind: Deployment
          namespace: behrang
          resourceName: franky-angular-starter-dev
          containerName: franky-angular-starter-dev
          keyKind: ${{ vars.MO_API_KIND__DEVELOP }}
          token: ${{ secrets.MO_API_TOKEN__f22d1e57db55edefd5ac__DEVELOP }}
      - id: releaseWithMogenius-dfd1866c8c25e2f0247c
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__DEVELOP }}:${{ env.VERSION }}
          kind: Deployment
          namespace: franky-test-space
          resourceName: frankytest1234
          containerName: frankytest1234
          keyKind: ${{ vars.MO_API_KIND__DEVELOP }}
          token: ${{ secrets.MO_API_TOKEN__dfd1866c8c25e2f0247c__DEVELOP }}
      - id: releaseWithMogenius-74952ac990137da76c9f
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__DEVELOP }}:${{ env.VERSION }}
          kind: Deployment
          namespace: behrang
          resourceName: franky-war-hier
          containerName: franky-war-hier
          keyKind: ${{ vars.MO_API_KIND__DEVELOP }}
          token: ${{ secrets.MO_API_TOKEN__74952ac990137da76c9f__DEVELOP }}
